# Generated by Django 5.2.7 on 2025-10-25 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_executive_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
